# frozen_string_literal: true

# table brands
brand_attributes = [{
                        title: 'Xiaomi', bytitle: 'xiaomi',
                        img: 'abt-1.jpg', description: 'China'
                    },
                    {
                        title: 'Huawei', bytitle: 'huawei',
                        img: 'abt-3.jpg', description: 'China'
                    },
                    {
                        title: 'Apple', bytitle: 'apple',
                        img: 'abt-2.jpg', description: 'USA'
                    },
                    {
                        title: 'TeXet', bytitle: 'texet',
                        img: '', description: 'Russia'
                    },
                    {
                        title: 'ZTE', bytitle: 'zte',
                        img: '', description: 'China'
                    },
                    {
                        title: 'BlackBerry', bytitle: 'blackberry',
                        img: '', description: 'USA'
                    },
                    {
                        title: 'Motorola', bytitle: 'motorola',
                        img: '', description: 'USA'
                    },
                    {
                        title: 'YotaPhone', bytitle: 'yotaphone',
                        img: '', description: 'Russia'
                    },
                    {
                        title: 'Highscreen', bytitle: 'highscreen',
                        img: '', description: 'Russia'
                    }]

brand_attributes.each do |attr|
  Brand.create(attr) unless Brand.where(attr).first
end

# - - - - -

# table categories
china = Category.create(title: 'China', bytitle: 'china', keywords: 'china', description: 'from China')
xiaomi = Category.create(title: 'Xiaomi', bytitle: 'xiaomi', keywords: 'xiaomi', description: 'xiaomi', parent: china)
huawei = Category.create(title: 'Huawei', bytitle: 'huawei', keywords: 'huawei', description: 'huawei', parent: china)
zte = Category.create(title: 'ZTE', bytitle: 'zte', keywords: 'zte', description: 'zte', parent: china)

usa = Category.create(title: 'USA', bytitle: 'usa', keywords: 'usa', description: 'from USA')
apple = Category.create(title: 'Apple', bytitle: 'apple', keywords: 'apple', description: 'apple', parent: usa)
blackberry = Category.create(title: 'BlackBerry', bytitle: 'blackberry', keywords: 'blackberry', description: 'blackberry', parent: usa)
motorola = Category.create(title: 'Motorola', bytitle: 'motorola', keywords: 'motorola', description: 'motorola', parent: usa)

russia = Category.create(title: 'Russia', bytitle: 'russia', keywords: 'russia', description: 'from Russia')
teXet = Category.create(title: 'TeXet', bytitle: 'teXet', keywords: 'teXet', description: 'teXet', parent: russia)
yotaphone = Category.create(title: 'YotaPhone', bytitle: 'yotaphone', keywords: 'yotaphone', description: 'yotaphone', parent: russia)
highscreen = Category.create(title: 'Highscreen', bytitle: 'highscreen', keywords: 'highscreen', description: 'highscreen', parent: russia)
# - - - - - - - -

# table products
product_attributes = [
    {
        category_id: '2',
        brand_id: '1',
        title: 'Xiaomi Mi 9',
        bytitle: 'xiaomi-mi-9',
        content: '',
        price: 243,
        old_price: 487,
        status: 1,
        keywords: 'keywords',
        description: 'Xiaomi Mi 9 is the flagship smartphone with a large bezel-less screen and very powerful hardware. The gadget is equipped with a triple camera, and also has a fingerprint scanner built into the display. The presentation date of the mobile device is February 20, 2019',
        dimensions: '157.5 x 74.7 x 7.6 mm',
        weight: '173 g',
        os: 'Android 9.0 (Pie) + MIUI 10',
        processor: 'Eight-core Qualcomm SDM855 Snapdragon 855 (1 × 2.84 GHz Kryo 485 & 3 × 2.42 GHz Kryo 485 & 4 × 1.8 GHz Kryo 485)',
        main_cam: 'Triple 48 MP (f / 1.8, 1/2 ″, 0.8µm, Laser / PDAF) + 16 MP (f / 2.2, 13mm ultrawide, 1 / 3.0 ″, 1.0µm, Laser / PDAF) + 12 MP ( f / 2.2, 54mm telephoto, 1 / 3.6 ″, 1.0µm, Laser / PDAF, 2x optical zoom)',
        front_cam: '20 MP, f / 2.0, 0.9µm, HDR, video 1080p @ 30fps',
        battery: 'Li-Po 3300 mAh',
        img: 'x-1.png',
        hit: 1
    },
  {
      category_id: '2',
      brand_id: '1',
      title: 'Xiaomi Mi 9T',
      bytitle: 'xiaomi-mi-9t',
      content: '',
      price: 203,
      old_price: 407,
      status: 1,
      keywords: 'keywords',
      description: 'Xiaomi Mi 9T is a budget flagship with a retractable selfie camera. The smartphone is equipped with a triple main camera, as well as a powerful battery. The official presentation of the gadget took place on June 12, 2019.',
      dimensions: '156.7 x 74.3 x 8.8 mm',
      weight: '191 g',
      os: 'Android 9.0 (Pie) + MIUI 10',
      processor: 'Eight-core Qualcomm SDM730 Snapdragon 730 (2 × 2.2 GHz Kryo 470 Gold & 6 × 1.8 GHz Kryo 470 Silver)',
      main_cam: 'T  riple
48 MP (f / 1.8, 26mm wide, 1/2 ″, 0.8µm, PDAF)
8 MP (f / 2.4, 53mm telephoto, 1/4 ″, 1.12µm, PDAF, 2x optical zoom)
13 MP (f / 2.4, 12mm ultrawide, 1/3 ″, 1.12µm)',
      front_cam: 'Pop-up 20 MP, f / 2.2, 0.8µm, HDR, 1080p @ 30fps',
      battery: 'Li-Po 4000 mAh',
      img: 'x-2.png',
      hit: 1
  },
  {
      category_id: '2',
      brand_id: '1',
      title: 'Xiaomi Mi 9 Lite',
      bytitle: 'xiaomi-mi-9-lite',
      content: '',
      price: 122,
      old_price: 244,
      status: 1,
      keywords: 'keywords',
      description: 'Xiaomi Mi 9 Lite is the European version of the popular youth smartphone CC9. This model is equipped with a triple camera and has a spectacular glass case. The official announcement of this beautiful gadget took place on September 16, 2019.',
      dimensions: '156.8 x 74.5 x 8.7 mm',
      weight: '179 g',
      os: 'Android 9.0 (Pie) + MIUI 10',
      processor: 'Eight-core Qualcomm SDM710 Snapdragon 710 (2 × 2.2 GHz Kryo 360 Gold & 6 × 1.7 GHz Kryo 360 Silver)',
      main_cam: 'Triple
48 MP (f / 1.8, wide, 1/2 ″, 0.8µm, PDAF)
8 MP (ultrawide)
2 MP (depth sensor)',
      front_cam: '32 MP, f / 2.0, 0.8µm, HDR, 1080p @ 30fps',
      battery: 'Li-Po 4030 mAh',
      img: 'x-3.png',
      hit: 1
  },
  {
      category_id: '2',
      brand_id: '1',
      title: 'Xiaomi Mi 9SE',
      bytitle: 'xiaomi-mi-9SE',
      content: '',
      price: 203,
      old_price: 407,
      status: 1,
      keywords: 'keywords',
      description: 'An advanced smartphone with an excellent camera is the XIAOMI Mi 9 SE. The device is running a modern Android 9.0 OS, so all popular applications and games are available. The model has a Snapdragon 712 processor and 6 GB of RAM, which ensures high performance. For data storage, 64 GB of memory is provided, in which you can store several dozen films in high resolution',
      dimensions: '70.5 х 147.5 х 7.45 mm',
      weight: '155 g',
      os: 'Android 9.0',
      processor: 'Eight-core Qualcomm Snapdragon 712, 2300 MHz',
      main_cam: 'Triple 48 Mp + 8 Mp + 13 Mp',
      front_cam: '20 Mp',
      battery: 'Li-Po 3070 mAh',
      img: 'x-4.png',
      hit: 1
  },
  {
      category_id: '3',
      brand_id: '2',
      title: 'Huawei P Smart Z',
      bytitle: 'huawei-p-smart-z',
      content: '',
      price: 105,
      old_price: 211,
      status: 1,
      keywords: 'keywords',
      description: 'The Huawei P smart Z device is unique in that it does not have a front camera on the front panel and is equipped with a selfie module that leaves the upper part of the case',
      dimensions: '77.26x163.45x8.85 mm',
      weight: '197 g',
      os: 'Android 9.0',
      processor: 'HiSilicon Kirin 710, 2200 MHz',
      main_cam: 'Double 16 Mp + 2 Mp',
      front_cam: '16 Mp',
      battery: '4000 mAh',
      img: 'h-1.png',
      hit: 1
  },
  {
      category_id: '3',
      brand_id: '2',
      title: 'Huawei P30 Pro',
      bytitle: 'huawei-p30-pro',
      content: '',
      price: 407,
      old_price: 814,
      status: 1,
      keywords: 'keywords',
      description: 'To take photos of professional quality, you no longer need to carry a bulky “SLR” and draw contrasts in graphic editors. Entrust the pictures to your new Huawei P30 Pro: its camera from the legendary Leica brand with four lenses and a resolution of 40 megapixels is capable of capturing even more stunning views into the frame than previous models of the brand. And the spectral sensor will ensure accurate color reproduction even at night. Of course, not only the camera in it is worthy of attention',
      dimensions: '	158 x 73.4 x 8.41 mm',
      weight: '192 g',
      os: 'Android 9',
      processor: 'Eight-core Kirin 980, 2x2.6 + 2x1.92 + 4x1.8 GHz',
      main_cam: 'Triple 40Mp + 20Mp + 8Mp',
      front_cam: '32 Mp',
      battery: '4200 mAh',
      img: 'h-2.png',
      hit: 1
  },
  {
      category_id: '3',
      brand_id: '2',
      title: 'Huawei Nova 5z',
      bytitle: 'huawei-nova-5z',
      content: '',
      price: 227,
      old_price: 455,
      status: 1,
      keywords: 'keywords',
      description: 'Huawei Nova 5z is a smartphone from a popular brand with excellent parameters. The device received a camera with four lenses, a powerful and high-quality processor, as well as a battery with high capacity. In addition, the front camera has as many as 32 MP. The announcement of the model took place on October 21, 2019',
      dimensions: '156.1 x 73.9 x 8.3 mm',
      weight: '178 g',
      os: 'Android 9.0 (Pie) + EMUI 9.1',
      processor: 'Eight-core HiSilicon Kirin 810
(2 × 2.27 GHz Cortex-A76 and 6 × 1.88 GHz Cortex-A55)',
      main_cam: '48 MP (f / 1.8, 26mm wide, 1/2 ″, 0.8µm, PDAF)
8 MP (f / 2.4, ultrawide)
2 MP (f / 2.4, 27mm wide, separate macro camera)
2 MP (f / 2.4, depth sensor)',
      front_cam: '32 MP (f / 2.0), HDR, 1080p @ 30fps video recording',
      battery: 'Li-Po 4000 mAh',
      img: 'h-3.png',
      hit: 1
  },
  {
      category_id: '3',
      brand_id: '2',
      title: 'Huawei Y9 Prime',
      bytitle: 'huawei-y9-prime',
      content: '',
      price: 97,
      old_price: 195,
      status: 1,
      keywords: 'keywords',
      description: 'Dual main and front cameras help you take high-quality pictures. Depth of field function allows you to create portrait and landscape shots.he announcement of the model took place on 2018',
      dimensions: '157.2 x 75.3 x 7.89 mm',
      weight: '170 g',
      os: 'Android 8.0 Oreo',
      processor: 'Eight-core Huawei Kirin 659, four cores 2.36 GHz Cortex-A53 and four cores 1.7 GHz Cortex-A53',
      main_cam: 'Double 13 Mp + 2 Mp',
      front_cam: 'Double 8 Mp + 2 Mp',
      battery: '4000 mAh',
      img: 'h-4.png',
      hit: 1
  },
  {
      category_id: '6',
      brand_id: '4',
      title: 'iPhone Xr',
      bytitle: 'iphone-xr',
      content: '',
      price: 341,
      old_price: 683,
      status: 1,
      keywords: 'keywords',
      description: 'The new Liquid Retina display is Apple most advanced LCD display. Even faster Face ID. The most powerful and smart iPhone processor. And an amazing camera. iPhone XR - the epitome of beauty and intelligence',
      dimensions: '150.9 x 75.7 x 8.3 mm',
      weight: '194 g',
      os: 'iOS 13',
      processor: 'A12 bionic, 2nd Generation Neural Engine',
      main_cam: '12 Mp',
      front_cam: '7 Mp',
      battery: '2942 mAh',
      img: 'a-1.png',
      hit: 1
  },
  {
      category_id: '6',
      brand_id: '4',
      title: 'iPhone X',
      bytitle: 'iphone-x',
      content: '',
      price: 407,
      old_price: 814,
      status: 1,
      keywords: 'keywords',
      description: 'The all-new 5.8-inch Super Retina display, which fits comfortably in your hand and looks amazing, is the iPhone X. The display and the elegantly rounded corners at the corners are even better integrated - this was achieved using several unique technologies. The innovative OLED panel fills the screen to the very edges - due to the tiered placement of chips and a new approach to the location of the controller. The pixels in the corners of the display are smoothed out at the subpixel level, so the borders are not distorted and look even',
      dimensions: '143.6 x 70.9 x 7.7 mm',
      weight: '174 g',
      os: 'iOS 13',
      processor: 'Six-core Apple A11 Bionic + M11 motion coprocessor',
      main_cam: 'Double 12 Mp + 12 Mp',
      front_cam: '7 Mp',
      battery: '2716 mAh',
      img: 'a-2.png',
      hit: 1
  },
  {
      category_id: '6',
      brand_id: '4',
      title: 'iPhone 11',
      bytitle: 'iphone-11',
      content: '',
      price: 488,
      old_price: 977,
      status: 1,
      keywords: 'keywords',
      description: 'The new system of two cameras will not leave any of your friends behind the scenes. The fastest iPhone processor and powerful battery will allow you to do more and spend less time on recharging. And the highest quality video on the iPhone means your stories will become even brighter and more detailed',
      dimensions: '150.9 x 75.7 x 8.3 mm',
      weight: '194 g',
      os: 'iOS 13',
      processor: 'Apple A13 Bionic',
      main_cam: 'Double 12 Mp + 12 Mp',
      front_cam: '12 Mp',
      battery: '3110 mAh',
      img: 'a-3.png',
      hit: 1
  },
  {
      category_id: '6',
      brand_id: '4',
      title: 'iPhone 8',
      bytitle: 'iphone-8',
      content: '',
      price: 203,
      old_price: 407,
      status: 1,
      keywords: 'keywords',
      description: 'For the first time, the front and back panels of the iPhone are made of glass. The most popular camera has been improved. Installed the smartest and most powerful processor ever created for the iPhone. Without wires, the charging process becomes elementary. And augmented reality opens up unprecedented opportunities so far. iPhone 8. The new generation of iPhone',
      dimensions: '138,4 x 67,3 x 7.3 mm',
      weight: '148 g',
      os: 'iOs13',
      processor: 'Six-core Apple A11 Bionic + M11 motion coprocessor',
      main_cam: '12 Mp',
      front_cam: '7 Mp',
      battery: '1821 mAh',
      img: 'a-4.png',
      hit: 1
  },
  {
      category_id: '10',
      brand_id: '7',
      title: 'TeXet ТМ-5583 Pay 5.5 3G',
      bytitle: 'texet-tm-5583-pay-5.5-3g',
      content: '',
      price: 41,
      old_price: 82,
      status: 1,
      keywords: 'keywords',
      description: 'The TM-5583 smartphone supports all basic communications: high-speed 3G Internet, through which the user has access to free instant messaging systems, as well as voice and video communications, Wi-Fi, Bluetooth 4.0. Integrated GPS allows you to use the device as a full-fledged navigator, and the uninterrupted operation of the device is supported by a 2850 mAh Li-ion battery',
      dimensions: '150.5 x 73.3 x 10.2 mm',
      weight: '143 g',
      os: 'Android 8.1 Oreo (GO edition)',
      processor: 'Four-core MediaTek MT6739WA, 1300 MHz',
      main_cam: '8 Mp',
      front_cam: '8 Mp',
      battery: '2850 mAh',
      img: 't-1.png',
      hit: 1
  },
  {
      category_id: '10',
      brand_id: '7',
      title: 'TeXet TM-5003',
      bytitle: 'texet-tm-5003',
      content: '',
      price: 24,
      old_price: 49,
      status: 1,
      keywords: 'keywords',
      description: 'With nostalgia for the past summer, teXet presents the new bright, sunny smartphone teXet TM-5003. This mobile gadget is specially designed for active youth. The color concept is defined by three fashionable colors: juicy scarlet, bright lime green and classic dark blue.',
      dimensions: '145 х 71,5 х 9.3 mm',
      weight: '140 g',
      os: 'Android 5.1',
      processor: 'Four-core, MediaTek MT6580, Cortex A7, 1.3 GHz GPU: dual-core, Mali-400 MP',
      main_cam: '5 Mp',
      front_cam: '1.3 Mp',
      battery: 'Li-Ion, 1800 mAh',
      img: 't-2.png',
      hit: 1
  },
  {
      category_id: '10',
      brand_id: '7',
      title: 'TeXet TM-5583',
      bytitle: 'texet-tm-5583',
      content: '',
      price: 36,
      old_price: 73,
      status: 1,
      keywords: 'keywords',
      description: 'The Texet TM-5583 smartphone has a classic design. The body color of the mobile device is black. The dual main camera with autofocus allows you to shoot photos and videos with high quality. There is also a 5-megapixel front camera',
      dimensions: '150.5 x 73.3 x 10.2 mm',
      weight: '143 g',
      os: 'Android 8.1 Oreo (GO edition)',
      processor: 'Four-core MediaTek MT6739WA, 1300 MHz',
      main_cam: '8 Mp',
      front_cam: '8 Mp',
      battery: '2850 mAh',
      img: 't-3.png',
      hit: 1
  },
    {
        category_id: '4',
        brand_id: '3',
        title: 'ZTE Axon 10 Pro 5G',
        bytitle: 'zte-axon-10-pro-5g',
        content: '',
        price: 306,
        old_price: 616,
        status: 1,
        keywords: 'keywords',
        description: 'ZTEs first 5G smartphone. There are two versions with different memory sizes: 6 GB + 128 GB and 12 GB + 256 GB. It runs on a Snapdragon 855 processor. Work in 5G networks is made possible thanks to the Snapdragon X50 modem',
        dimensions: '159.2 x 73.4 x 7.9 mm',
        weight: '175 g',
        os: 'Android 9.0',
        processor: 'Eight-core Snapdragon 855 2800 MHz',
        main_cam: 'Triple, 48 Mp + 20 Mp + 8 Mp',
        front_cam: '19.66 Mp',
        battery: '4000 mAh',
        img: 'z-1.png',
        hit: 1
    },
    {
        category_id: '4',
        brand_id: '3',
        title: 'ZTE Blade A7 2020',
        bytitle: 'zte-blade-a7-2020',
        content: '',
        price: 57,
        old_price: 114,
        status: 1,
        keywords: 'keywords',
        description: 'It is noteworthy that with its good characteristics, as well as the presence of NFC, this smartphone does not have a fingerprint scanner. ZTE Blade A7 2020 can identify its owner in a more convenient way - by face. The front camera, which is 8-megapixel, is responsible for face recognition. Powered by an 8-core Mediatek Helio P22 processor (4 cores 1500 MHz and 4 cores 2000 MHz). This is a good processor for such an inexpensive smartphone.',
        dimensions: '155 x 72.7 x 8.95 mm',
        weight: '164 g',
        os: 'Android 9.0',
        processor: 'Eight-core Mediatek Helio P22 4x2000 MHz + 4x1500 MHz',
        main_cam: 'Tripple 16 Mp + 8 Mp + 2 Mp',
        front_cam: '8 Mp',
        battery: '4000 mAh',
        img: 'z-2.png',
        hit: 1
    },
    {
        category_id: '4',
        brand_id: '3',
        title: 'ZTE Blade A5 2020',
        bytitle: 'zte-blade-a5-2020',
        content: '',
        price: 51,
        old_price: 102,
        status: 1,
        keywords: 'keywords',
        description: 'Budget smartphone on a cheap processor. Unlike the ZTE Blade A5 2019, the new ZTE Blade A5 2020 has become larger, the camera is now dual, the battery is better. Both work on an 8-core UNISOC SC9863A processor (8 Cortex-A55 1600 MHz cores, 28-nanometer process technology, PowerVR GE8322 graphics)',
        dimensions: '156.7 x 72.6 x 8 mm',
        weight: '155 g',
        os: 'Android 9.0',
        processor: 'Eight-core UNISOC SC9863A 8x1600 MHz',
        main_cam: 'Double 13 Mp + 2 Mp',
        front_cam: '7 Mp',
        battery: '3200 mAh',
        img: 'z-3.png',
        hit: 1
    },
    {
        category_id: '7',
        brand_id: '5',
        title: 'BlackBerry KEY2',
        bytitle: 'blackberry-key2',
        content: '',
        price: 406,
        old_price: 812,
        status: 1,
        keywords: 'keywords',
        description: 'BlackBerry KEY2 in a thinner and lighter, but at the same time extremely durable case is most convenient to use anytime, anywhere',
        dimensions: '151.4 x 71.8 x 8.5 mm',
        weight: '168 g',
        os: 'Android 8.1 Oreo',
        processor: 'Eight-core Qualcomm Snapdragon 660 2200 MHz',
        main_cam: 'Double 12 Mp + 12 Mp',
        front_cam: '8 Mp',
        battery: '3500 mAh',
        img: 'b-1.png',
        hit: 1
    },
    {
        category_id: '7',
        brand_id: '5',
        title: 'BlackBerry KeyOne',
        bytitle: 'blackberry-Keyone',
        content: '',
        price: 243,
        old_price: 487,
        status: 1,
        keywords: 'keywords',
        description: 'The BlackBerry KEYone smartphone is a unique device that continues the traditions of the Canadian company. Under its display with an unusual aspect ratio of 2: 3 is a physical QWERTY-keyboard, which significantly speeds up typing and even allows you to edit documents without copying to a computer. She received new mechanisms with a reduced stroke length and smooth translucent caps with beveled edges. Due to this, clarity of pressing is ensured and the number of errors is reduced',
        dimensions: '149.3 x 72.5 x 9.4 mm',
        weight: '180 g',
        os: 'Android 7.1 Nougat',
        processor: 'Eight-core Qualcomm MSM8953 Snapdragon 625 2000 MHz',
        main_cam: '12 Mp',
        front_cam: '8 Mp',
        battery: '3505 mAh',
        img: 'b-2.png',
        hit: 1
    },
    {
        category_id: '8',
        brand_id: '6',
        title: 'Motorola Moto E6 Plus ',
        bytitle: 'motorola-moto-e6-plus ',
        content: '',
        price: 89,
        old_price: 178,
        status: 1,
        keywords: 'keywords',
        description: 'The dual main camera with a resolution of 13 megapixels allows you to create vivid and almost professional photos, including beautiful portraits with blur effect. In addition, thanks to the 8-megapixel front camera, you will always be good at taking pictures',
        dimensions: '155.6 x 73.06 x 8.6 mm',
        weight: '149.7 g',
        os: 'Android 9.0 Pie',
        processor: 'Eight-core MediaTek Helio P22 2000 MHz',
        main_cam: 'Double 13 Mp + 2 Mp',
        front_cam: '8 Mp',
        battery: '3000 mAh',
        img: 'm-1.png',
        hit: 1
    },
    {
        category_id: '8',
        brand_id: '6',
        title: 'Motorola Moto G8 Plus',
        bytitle: 'motorola-moto-g8-plus',
        content: '',
        price: 120,
        old_price: 240,
        status: 1,
        keywords: 'keywords',
        description: 'The 48 megapixel sensor with laser autofocus instantly focuses on the subject. Quad Pixel technology (combining 4 pixels into one), which achieves a point size of 1.6 microns, and night shooting mode increase photosensitivity in low light and provide stunning, effective photos at any time - day or night',
        dimensions: '158.35 x 75.83 x 9.09 mm',
        weight: '188 g',
        os: 'Android 9.0 Pie',
        processor: 'Eight-core Qualcomm Snapdragon 665 2000 MHz',
        main_cam: 'Triple 48 Mp + 16 Mp + 5 Mp',
        front_cam: '25 Mp',
        battery: '4000 mAh',
        img: 'm-2.png',
        hit: 1
    },
    {
        category_id: '8',
        brand_id: '6',
        title: 'Motorola Moto E5 Play',
        bytitle: 'motorola-moto-e5-play',
        content: '',
        price: 40,
        old_price: 81,
        status: 1,
        keywords: 'keywords',
        description: 'The 5.3-inch Max Vision screen offers you a wide view with a narrow bezel. Unlike traditional displays, Max Vision has an aspect ratio of 18: 9, so you can see more. You will scroll less web pages and be able to see more on one screen. Enjoy a wide picture in your favorite landscape games. Touch the fingerprint scanner to instantly wake up the phone, unlock and lock it. The scanner is conveniently located in the famous logo on the back of the phone. You may not even notice it until you need to use it. Taking great photos is easy with a 5 megapixel selfie camera and flash. In addition, the main 8-megapixel camera focuses instantly, so you will never miss a moment. Your photos will look great indoors, in low light conditions and on cloudy days thanks to automatic enhancement',
        dimensions: '147.9 x 71.2 x 9.2 mm',
        weight: '150 g',
        os: 'Android 8.1 Oreo (GO edition)',
        processor: 'Four-core Qualcomm Snapdragon 425 1400 MHz',
        main_cam: '8 Mp',
        front_cam: '5 Mp',
        battery: '2300 mAh',
        img: 'm-3.png',
        hit: 1
    },
    {
        category_id: '11',
        brand_id: '8',
        title: 'YotaPhone 2',
        bytitle: 'yotaphone-2',
        content: '',
        price: 146,
        old_price: 292,
        status: 1,
        keywords: 'keywords',
        description: 'The black YotaPhone 2 smartphone is an original and unusual device. Its first external difference is the presence on the body of two screens at once. The main display is based on AMOLED technology, characterized by a diagonal of 5 inches and a resolution of 1920 by 1080 pixels. The diagonal of the additional matrix is ​​4.7 inches, it is based on electronic ink technology, that is, it is ideal for reading books, displaying time, weather and other information, and it needs energy only when updating the page.
The frequency of the YotaPhone 2 processor is 2.2 GHz with 4 working cores, the amount of RAM is limited to a couple of gigabytes. Both displays are protected by Gorilla Glass 3, which makes it possible to operate in harsh conditions without fear of cracks and scratches. There is the possibility of using the phone as a navigator, communication is maintained not only with the satellites of the international GPS system, but also with the domestic development of GLONASS, which guarantees the highest positioning accuracy',
        dimensions: '144,9 х 69,4 х 8,95 mm',
        weight: '145 g',
        os: 'Android 4.4 KitKat',
        processor: 'Four-core Qualcomm 2200 MHz',
        main_cam: '8 Mp',
        front_cam: '2 Mp',
        battery: '2500  mAh',
        img: 'y-1.png',
        hit: 1
    },
    {
        category_id: '11',
        brand_id: '8',
        title: 'YotaPhone 3',
        bytitle: 'yotaphone-3',
        content: '',
        price: 243,
        old_price: 487,
        status: 1,
        keywords: 'keywords',
        description: 'The third generation smartphone with two active screens, developed by Yota Devices. The smartphone received a 5.5-inch primary AMOLED display with FullHD resolution, as well as a 5.2-inch additional HD-screen, made by E-Ink technology, on the back cover. Installed YOTA OS consists of android and proprietary OS of Russian developers serving the e-ink display',
        dimensions: '153.6 х 75.2 х 7.9 mm',
        weight: '170 g',
        os: 'Android 7.1',
        processor: 'Eight-core Snapdragon 625 2200 MHz',
        main_cam: '13 Mp',
        front_cam: '12 Mp',
        battery: '3300 mAh',
        img: 'y-2.png',
        hit: 1
    },
    {
        category_id: '12',
        brand_id: '9',
        title: 'Highscreen Max 3',
        bytitle: 'highscreen-max-3',
        content: '',
        price: 105,
        old_price: 210,
        status: 1,
        keywords: 'keywords',
        description: 'The new Highscreen Max 3 smartphone is an improved model of Highscreen Power Five Max 2. Management of Max 3 has become even more convenient thanks to the updated advanced version of Android 9. Traditionally for the Highscreen brand, the device has a “clean” Android, which means that pre-installed applications are reduced to the minimum possible, without overflowing the memory and not loading the interface, giving the owner the right to choose',
        dimensions: '157.5 x 76.9 x 10.3 mm',
        weight: '221 g',
        os: 'Android 9.0',
        processor: 'Eight-core MT6765 2300 MHz',
        main_cam: '16 Mp',
        front_cam: '8 Mp',
        battery: '5000 mAh',
        img: 'hi-1.png',
        hit: 1
    },
    {
        category_id: '12',
        brand_id: '9',
        title: 'Highscreen Ice 2',
        bytitle: 'highscreen-ice-2',
        content: '',
        price: 81,
        old_price: 162,
        status: 1,
        keywords: 'keywords',
        description: 'Smartphone Highscreen ICE 2 - a stylish smartphone with a unique design. The screen and the back of the Highscreen Ice 2 smartphone are covered with Gorilla Glass 3 protective glass, giving the device not only protection from scratches, but also a fantastically beautiful appearance',
        dimensions: '138 x 67.6 x 8.7 mm',
        weight: '135 g',
        os: 'Android 4.4',
        processor: 'Eight-core MT6592 1700 MHz',
        main_cam: '13 Mp',
        front_cam: '2 Mp',
        battery: '2500 mAh',
        img: 'hi-2.png',
        hit: 1
    },
    {
        category_id: '12',
        brand_id: '9',
        title: 'Highscreen Thunder',
        bytitle: 'highscreen-thunder',
        content: '',
        price: 73,
        old_price: 146,
        status: 1,
        keywords: 'keywords',
        description: 'The black Highscreen Thunder smartphone attracts attention with its stylish appearance and thoughtful selection of electronic components. It also features high quality built-in cameras (rear 13 MP, front 5 MP) and powerful, clear sound, which is provided for both the headphones and the built-in speaker. All the device’s energy needs are provided by a battery with a serious capacity of 3500 mAh.
The highscreen Thunder smartphone with a screen diagonal of 5.5 "in black can offer the user a long-term memory of 16 GB for downloading multimedia content and programs. The device’s screen is equipped with AGC Dragontrail coating that can effectively protect it from signs of operation, including unpleasant scratches. Being qualitative manufactured and enjoyable in daily use, this smartphone will be the best choice for purchase as a presentation or for personal use',
        dimensions: '150 x 74 x 8.5  mm',
        weight: '153 g',
        os: 'Android 6.0',
        processor: 'Eight-core MT6723 1300 MHz',
        main_cam: '13 Mp',
        front_cam: '5 Mp',
        battery: '3500 mAh',
        img: 'hi-3.png',
        hit: 1
    }
]

product_attributes.each do |attr|
  Product.create(attr) unless Product.where(attr).first
end
